[build]
publish = 'public'
command = './scripts/run.sh build $BUILD_OUTPUT_PATH'
[build.environment]
HUGO_VERSION = '0.104.1'
HUGO_BASEURL = 'https://docs.snowplow.io/accelerators/web/'
BUILD_OUTPUT_PATH = '/accelerators/web/'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'

[context.deploy-preview]
command = './scripts/run.sh build $BUILD_OUTPUT_PATH $DEPLOY_PRIME_URL'

[context.branch-deploy]
command = './scripts/run.sh build $BUILD_OUTPUT_PATH $DEPLOY_PRIME_URL'

[[redirects]]
from = "/*"
to = "/accelerators/hybrid/:splat"
force = true
status = 301
